spring.application.name=MilkTeaShop
server.port=8088

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/milkteashop
spring.datasource.username=postgres
spring.datasource.password=Ngocmai@1004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret-key=milkteabcdefghijklmnopq_secure_key_padding_to_512bits_xxxx
jwt.expired=900000
