spring.application.name=employee

server.port=8088
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Ngocmai@1004
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=MySuperSecretKey1234567890AbcDefGhiJklMnoPqrStuVwxYz
jwt.expiration=86400000

cloud-name=dslb9vvli
api-key=114465867622912
api-secret=JbLHojt__XVXMVI6dgTMOKGPlVA
